name: CI

on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main
      
      # Install Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Giving executable permission
        run: chmod +x ./project/tests.sh

      # Runs the project build
      - name: Run the project build
        run: |
            ./project/tests.sh
